// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function CreateFileByDirectory(arg1, arg2) {
  return window['go']['main']['App']['CreateFileByDirectory'](arg1, arg2);
}

export function DeleteFileByDirectory(arg1) {
  return window['go']['main']['App']['DeleteFileByDirectory'](arg1);
}

export function FilesInDirectory(arg1) {
  return window['go']['main']['App']['FilesInDirectory'](arg1);
}

export function FindNotesByFilename(arg1) {
  return window['go']['main']['App']['FindNotesByFilename'](arg1);
}

export function MaximiseApp() {
  return window['go']['main']['App']['MaximiseApp']();
}

export function MinimiseApp() {
  return window['go']['main']['App']['MinimiseApp']();
}

export function OpenFileByDirectory(arg1) {
  return window['go']['main']['App']['OpenFileByDirectory'](arg1);
}

export function UpdateFileByDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateFileByDirectory'](arg1, arg2, arg3);
}
